### ISSUE TITLE
either dataset or pretrained model

### ISSUE THREAD

**Issue by pribadihcr** [cameronfabbri/Underwater-Color-Correction#1]
hi @cameronfabbri ,
Is there the dataset that can we try it or the pretrained model?

**Comment by cameronfabbri** [comment]
Hi, yes you can download the dataset [here](http://www-users.cs.umn.edu/~fabbr013/projects/underwater.html).

You can also find this link on the [project page](http://www-users.cs.umn.edu/~fabbr013/projects/underwater.html). I'll upload a pretrained model later today.

**Comment by Xiaodong-Bran** [comment]
@cameronfabbri  
Hi , is it possible to upload the test image with the ground truth i.e. the image before distortion?

Thanks !

**Comment by cameronfabbri** [comment]
@Xiaodong-Bran actually the test images I am using have no ground truth. That's the difficulty in the underwater domain, we only have access to the distorted images, i.e those are "ground truth".

**Comment by Xiaodong-Bran** [comment]
@cameronfabbri 
Thanks for your reply. Understood. 
By the way, do you know why my training result often image result in red hue ( with your provided training pair,around 100 epochs) ?

I found your pretrained model is around 100,000 step with batch-size 32, that will be around 500 epochs right? 
Do I need to keep on training these models?

Thanks!
