### ISSUE TITLE
About the convert_video.py

### ISSUE THREAD

**Issue by balzac001** [cameronfabbri/Underwater-Color-Correction#7]
The netG function is not found if I use the pix2pix network, how I can change it? If I use the resnet network, the netG function is netG(x), not netG(x, loss_method)!

**Comment by noahratliff** [comment]
Is there any resolution to this issue? I am having the same problem.

**Comment by noahratliff** [comment]
@balzac001

**Comment by cameronfabbri** [comment]
This has been resolved, `convert_video.py` should work now.
